# Generated by Django 4.0.4 on 2022-05-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0002_remove_profile_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
